const holes = document.querySelectorAll('.hole');
const scoreBoard = document.querySelector('.score');
const moles = document.querySelectorAll('.mole');
const startBtn = document.querySelector('button');
let lastHole;
let timeUp = false;
let score = 0;

// Get the random time (between min and max)
function randomTime(min, max) {
    return Math.round(Math.random() * (max - min) + min);
}
// Get random hole
function randomHole(holes) {
    const idx = Math.floor(Math.random() * holes.length);
    const hole = holes[idx];
    // Prevent getting the same hole twice in a row 
    if (hole === lastHole) {
        console.log('THE SAME ONE');
        return randomHole(holes);
    }
    lastHole = hole;
    return hole;
}

// Make the mole show in the hole
function peep() {
    const time = randomTime(500, 1000);
    const hole = randomHole(holes);
    hole.classList.add('up');
    setTimeout(() => {
        hole.classList.remove('up');
        if (!timeUp) peep();
    }, time);
}

// Reset the score and start the new game
function startGame() {
    startBtn.style.visibility = 'hidden';
    score = 0;
    scoreBoard.textContent = 0;
    timeUp = false;
    peep();
    // Stop the game after 10s
    setTimeout(() => timeUp = true, 10000);
    setTimeout(() => startBtn.style.visibility = 'visible', 10000);

}

function bonk(e) {
    // Return if e.isTrusted = false (isTrusted returns true only if event was generated by a user action, not the script )
    if (!e.isTrusted) return;
    score++;
    this.parentNode.classList.remove('up');
    scoreBoard.textContent = score;
}

moles.forEach(mole => mole.addEventListener('click', bonk));
startBtn.addEventListener('click', startGame);